### PR TITLE
Use flex display on dialog windows

### PR DESCRIPTION
**Pull request by jevenski**
- Use flex display for dialog contents, and enable overflowing on the Y-axis if content height exceeds the max-height of windows.
- Define background color and border colors using CSS variables.
- Remove unused CSS rules.

### CODE REVIEW

**Comment by stickz** [comment]
What is the impact of this change? Do we need it in `v5.1` or can it wait until `v5.2`? I'm getting about ready to post Beta 3 once #2760 is merged. Test it then mark `v5.1` as stable to deploy to ten thousand clients.

**Comment by jevenski** [comment]
@koblack mentioned that things grow too big to fit in some of the dialog windows (https://github.com/Novik/ruTorrent/pull/2748#issuecomment-2425825286), so the scrolling needs to function properly. This can be a preparation for enlarged font size on mobile, so I think it can wait till v5.2

**Comment by n1ce-0ne** [comment]
this is exciting, i always read along, i still run an old version, im an avid fan of auto-dl irssi,
since you guys are smashing this i'd call about the only thing thats stopping another ten thousand clients is the lack of it in these new versions, nothing else comes close to it, serious, if you guys wanna put the icing on the cake someone needs to look into why it wont run on this, many will be running older versions to keep auto-dl, many would update if it existed on the latest releases,
just a thought!

**Comment by n1ce-0ne** [comment]
and before you say it.. just because the dev has abandoned it, doesn't mean many thousands stopped using it

**Comment by n1ce-0ne** [comment]
i'd help if i could, if its something you would consider in these new versions i'd put some time in to try fix it

**Comment by stickz** [comment]
@n1ce-0ne Send this link to your hosting provider or use the swizzin installation script (for personal usage) to install a compatible version of autodl with the latest ruTorrent. https://github.com/swizzin/autodl-rutorrent

**Comment by n1ce-0ne** [comment]
> @n1ce-0ne Send this link to your hosting provider or use the swizzin installation script (for personal usage) to install a compatible version of autodl with the latest ruTorrent. https://github.com/swizzin/autodl-rutorrent
oh wow thankyou very much, i didn't realise, keep up the great work all 😁😎🤩

**Pull request closed without merging**
