### PR TITLE
minor fixes

### PR DESCRIPTION
**Pull request by Micdu70**
- Remove fixed "width" value for task console
- Update "screenshots" and "spectrogram" plugins' translation (French)

### CODE REVIEW

**Comment by Novik** [comment]
> Hide "screenshots" and "spectrogram" plugins' buttons in task console when they should be hidden

Describe corresponding case more detail, please.
How I may reproduce situation, when these buttons are visible, but should be hidden ?

**Comment by Micdu70** [comment]
> Describe corresponding case more detail, please.
> How I may reproduce situation, when these buttons are visible, but should be hidden ?

1) Start ruTorrent
2) Select a torrent containing music or video file(s)
3) Go in "Files" tab and left-click on a music or video file -> MediaInfo

You see "screenshots" and "spectrogram" buttons in the task console window

**Comment by Novik** [comment]
> You see "screenshots" and "spectrogram" buttons in the task console window

No, I can't see them:

2020-11-27_16h12_23

Both plugins "screenshots" and "spectrogram" are installed.

**Comment by Micdu70** [comment]
My issue about "screenshots" and "spectrogram" plugins" buttons only exist on custom some custom themes. ;)

PR modified!

**Pull request merged**
