### PR TITLE
Adjust dialog window structure

### PR DESCRIPTION
**Pull request by jevenski**
This commit addresses styling issue of the header part of dialog windows. It also fixes the 4th bug in this latest feedback: https://github.com/Novik/ruTorrent/issues/2721#issuecomment-2403928876 . This issue happens because the background images are 600px width, but our new dialog windows can grow over that width, so the extra part becomes a desert. So I cropped off the additional part of those background images, kept only the icon part, and used CSS background color to implement the same effect. For the Oblivion theme, a CSS gradient background is used to mimic the original background.

- Changes are done to the header section, separating the background and the window icon to different levels of HTML.
- Make theme adaptions, with the aime of decreasing CSS selector specificity and reducing code duplication.

### CODE REVIEW

**Comment by stickz** [comment]
@jevenski You can submit this change to `master`. If @koblack can test and confirm a resolution, I will push a hotfix.

**Comment by koblack** [comment]
Yes, I confirm it is fixed

image

**Comment by jevenski** [comment]
This branch was created based on the develop branch, and then rebased to the master branch using Github mobile app. Is this going to be a problem? Also, I saw the develop branch is 6 commits behind the master branch, do we leave it as is and merge all the hot fixes when doing a version upgrade?

**Comment by jevenski** [comment]
I'm keeping an eye on the issue reports these days, and going over some old issues to see if I can fix some of those. We might need to clean up the reports a bit before new issues arise. For example, this one (third-party plugin issue): https://github.com/Novik/ruTorrent/issues/2631, and this one (already merged to master): https://github.com/Novik/ruTorrent/issues/2679.

**Comment by stickz** [comment]
> I'm keeping an eye on the issue reports these days, and going over some old issues to see if I can fix some of those. We might need to clean up the reports a bit before new issues arise. For example, this one (third-party plugin issue): #2631, and this one (already merged to master): #2679.

Done, I closed off those 2 issue reports and one more.

**Comment by jevenski** [comment]
The 2nd and the 5th issue have been resolved with the latest two commits. It would be appreciated if @koblack can take the trouble to test them again. The S-Table is still not perfect yet, though, with some issues like body column width unaligned with the header. I'll try to polish that part in v5.1.

**Comment by koblack** [comment]
Thanks, I checked it and it's fine now

image

image

**Comment by jevenski** [comment]
Hi @stickz, what do you think about this one? Anything else I should modify in order to get this PR merged?

**Comment by stickz** [comment]
> Hi @stickz, what do you think about this one? Anything else I should modify in order to get this PR merged?

I'll review it tomorrow. I had a family gathering to attend tonight. 
I just need to make sure everything works properly, before I click the green merge button.

**Comment by jevenski** [comment]
Enjoy the precious time with family!
I still have one question though. Once this commit becomes a hot fix to the master branch, can I rebase the develop branch immediately onto this commit, so that we can continue developing v5.1 based on this fix and thus avoid merge conflicts when push out v5.1?

**Comment by stickz** [comment]
Merged, going to do a release control (beta) version of v5.1. We will confirm everything works properly there.

**Pull request merged**
