### PR TITLE
Add Hostname plugin: adds hostname column to peers tab, resolve ip to hostname

### PR DESCRIPTION
**Pull request by rozhuk-im**
Old version and screenshot: http://netlab.dhis.org/wiki/ru:software:rtorrent:rutorrent_hostname

### CODE REVIEW

**Comment by Novik** [comment]
Plugin GeoIP already has this functionality.

**Comment by rozhuk-im** [comment]
It more heavy and require more deps to work.

**Comment by Novik** [comment]
> It more heavy

JS code of GeoIP plugin - 6.1K, of your plugin - 4.8K. 
IMHO 1.3K of difference is not "more heavy".

> and require more deps to work.

This is not true. In minimal configuration (only $retrieveHost = true) plugin GeoIP has only one dependence - php extension 'json'. Your plugin has this dependence too.

Sorry, but I don't need your plugin in the ruTorrent repo.

**Comment by rozhuk-im** [comment]
GeoIP replace IP address to hostname, this add host name, so user can see both IP and HOSTNAME.

**Comment by Micdu70** [comment]
@rozhuk-im Can you please create a new git repo with this plugin only?
(name's example: hostname-rutorrent)
I will update the ruTorrent wiki after. ;)

**Comment by rozhuk-im** [comment]
Ok, I need rework readme.txt to readme.md in this case :)

**Comment by rozhuk-im** [comment]
https://github.com/rozhuk-im/rutorrent-hostname

**Pull request closed without merging**
