### PR TITLE
Update extsearch engines

### LINKED ISSUE #1517: add nyaa.si extsearch
How to replace sukebei.nyaa.se by nyaa.si  for plugins extsearch? Because I changed the URL but the search does not work

thank you

### PR DESCRIPTION
**Pull request by Micdu70**
RIP Nyaa and Torrent411

EDIT: Added Nyaa.si (sukebe and normal website) as Nyaa alternative.
EDIT2: Close #1517

### CODE REVIEW

**Comment by minibombardo** [comment]
nyaa is here https://nyaa.si/ thanx for add in the plugin

**Comment by Micdu70** [comment]
@minibombardo Yes it's a nice alternative to the real -dead- Nyaa. Added! =)

Torrent411 alternative exists too ( https://t411.si/ ) but don't think it shoud be added in extsearch plugin...

**Comment by minibombardo** [comment]
I think t411.si can be added to the search.

**Comment by Micdu70** [comment]
@minibombardo I'm on it, but the download link can not be get (or guessed) from t411.si search page (yet - hope changing that)... maybe in the next update => https://twitter.com/t411_v2/status/895321639365222400

**Pull request merged**
