### PR TITLE
ENV configuration in config.php

### PR DESCRIPTION
**Pull request by nelu**
Add ability to configure persistent data paths and network services from ENVIRONMENT configuration variables.

### CODE REVIEW

**Comment by stickz** [comment]
We will merge this in ruTorrent `v5.2`.

**Comment by davorb** [comment]
I think it would make sense to also document this somewhere

**Comment by stickz** [comment]
> I think it would make sense to also document this somewhere

Agreed. @nelu Could you update the public accessible wiki? https://github.com/Novik/ruTorrent/wiki/Config

**Comment by nelu** [comment]
I edit the wiki page with a new sample config, hope is sufficient.

**Comment by stickz** [comment]
> I edit the wiki page with a new sample config, hope is sufficient.

Thanks this is good. Please see this change to the `develop` branch. I've updated it.

**Pull request merged**
