### PR TITLE
Added new search engines

### PR DESCRIPTION
**Pull request by emuhendis**
1. Yify  torrents via https://yts.ag/api
2. Rarbg torrent via https://torrentapi.org/apidocs_v2.txt

### CODE REVIEW

**Comment by Novik** [comment]
Thanks. But what about corresponding icons?

**Comment by emuhendis** [comment]
Added icons.

**Comment by Micdu70** [comment]
hm... "RARbgTorrentAPorg.php" should be named "RARbgTorrentAPI.php", because it gives this php error:

`PHP Fatal error:  Uncaught Error: Class 'RARbgTorrentAPorgEngine' not found [...]`

**Comment by Novik** [comment]
Fixed, thanks.

**Pull request merged**
