### PR TITLE
Fix torrent deleted without confirmation

### PR DESCRIPTION
**Pull request by jevenski**
- This commit fixes an error that torrent(s) get deleted without confirmation, even if the option is checked in the options. Previously, the delete action worked as expected using the delete button in the top menu, asking for confirmation before taking actual action. However, using the "remove" option in the context menu or the `DEL` key on the keyboard would got the torrent(s) removed immediately. They were just not calling the correct remove function.
- Besides the correction of delete events handler, two other things were carried out by the way, although not on the scope of the entire app but just around the functions that were adjusted in this fix.
  1. Some ident related issues were picked out by the way, like mixing spaces with tabs on the same line.
  2. Documentations were added to some of the JS functions, according to my own understanding of the function. They might be incorrect, but can be polished while the project grows.

Related:
https://github.com/Novik/ruTorrent/issues/2596
https://github.com/Novik/ruTorrent/issues/2721#issuecomment-2394279265 (the part of accidentally tapping "remove" in the last paragraph)

### CODE REVIEW

**Comment by stickz** [comment]
Thanks!

**Comment by stickz** [comment]
@jevenski Could I ask a small favour? Could you backport just the delete key fix to the `v4.3` branch? I want to push out a version that Gentoo Linux can mark as stable. It will be a major milestone for the ruTorrent project to get a stability mark on Linux!

**Comment by jevenski** [comment]
> @jevenski Could I ask a small favour? Could you backport just the delete key fix to the `v4.3` branch? I want to push out a version that Gentoo Linux can mark as stable. It will be a major milestone for the ruTorrent project to get a stability mark on Linux!

Yes, sure thing. Just wanna confirm that we just need the correction on bringing up the confirmation dialog, *without* the indent and the documentation part?

**Comment by geopsllc** [comment]
On that topic, is anyone else seeing an issue where delete with data is doing the data removal but the torrent stays in the webpage list until a full page reload?

**Pull request merged**
