### PR TITLE
work around for file system which is marked as noexec fixes #997

### LINKED ISSUE #997: Failed to load plugins wich need external applications if partition is mounted with noexec flag
OpenMediaVault mounts it's NAS filesystem with the noexec flag. So if I where to install ruTorrent on in a Shared Folder this would make ruTorrent unable to load it's plugins due to the usage of `test.sh`

image

This could be avoided by letting `/bin/sh` load and execute `test.sh` instead of executing `test.sh` itself.

### PR DESCRIPTION
**Pull request by DipSwitch**
Fixes the problem of loading the plugins if ruTorrent is stored on a noexec file system.

### CODE REVIEW

**Comment by Novik** [comment]
You make something strange.
sh - c "/bin/sh test.sh"

1) You don't need to call 'sh' twice.
2) 'sh' maybe located outside /bin.

**Comment by DipSwitch** [comment]
Yeah I know but `new rXMLRPCCommand("execute", array( "sh ". escapeshellarg(addslash($path)."test.sh")." ".$exe." ".escapeshellarg($st).$add)));` and `new rXMLRPCCommand("execute", array( "sh", escapeshellarg(addslash($path)."test.sh"), $exe, escapeshellarg($st).$add))` didn't work neither.

**Comment by Novik** [comment]
Strange. Second case should work. Try to turn on logging into rtorrent. Something like
log.execute = /var/torrent/logs/execute.log
in rtorrent.rc

**Comment by DipSwitch** [comment]
Log:

	---
	sh '/media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/php/test.sh' php '/media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/share/settings/266375029' '/usr/bin/php'
	---
	sh: 0: Can't open '/media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/php/test.sh'

Tests:

	$ sudo su torrent -c "cat /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/php/test.sh"
	#!/bin/sh
	...

	$ ps aux | grep rtorrent
	torrent   1832  0.0  0.0  14556   688 ?        Ss   10:23   0:00 /usr/bin/dtach -n /tmp/rtorrent.dtach /usr/bin/rtorrent
	torrent   1833  5.0  0.2 206800 35320 pts/0    Ssl+ 10:23   0:16 /usr/bin/rtorrent

I'll look at it later today...

**Comment by DipSwitch** [comment]
Oke, after a fresh look I found out why the test wouldn't succeed without a double call to `sh`

    $req = new rXMLRPCRequest(new rXMLRPCCommand("execute", array( "sh", addslash($path)."test.sh", $exe, $st, $add)));

There was not suppose to be a dot between `$st` and `$add` since they where two arguments. And since we don't want sh to execute a command via the shell interpreter we don't have to `escapeshellarg` the arguments... So now they `log.error=...` prints:

	sh -c /usr/bin/id -u ; /usr/bin/id -G ; echo ~

	---
	Captured output:
	1002
	100 33 37 1001
	/media/218a6a64-a854-454b-9ce0-703f8d90b008/torrents
	--- Success ---

	sh /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/php/test.sh php /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/share/settings/989902797  '/usr/bin/php'
	--- Success ---

	sh /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/php/test.sh curl /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/share/settings/1574361650  '/usr/bin/curl'
	--- Success ---

	sh /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/php/test.sh pgrep /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/share/settings/476520996  '/usr/bin/pgrep'
	--- Success ---

	sh /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/php/test.sh unzip /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/share/settings/822823404  '/usr/bin/unzip'
	--- Success ---

	sh /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/php/test.sh unrar /media/218a6a64-a854-454b-9ce0-703f8d90b008/rutorrent/share/settings/1324848663  '/usr/bin/unrar'
	--- Success ---

The plugins load and there is no execution denial on the `test.sh` file although there is a `noexec` options on the mounted file system.

**Pull request merged**
