### PR TITLE
Snoopy: Add port to Host header

### LINKED ISSUE #1247: Error loading feeds RSS problems with https
Version rtorrent 0.9.6 rutorrent 3.7
cURL can get the right information from HTTPS RSS link.
However, the RSS plugins failed to load RSS link with https.
I can't add torrent link with https download link either.
But the RSS plugins can get the feeds from HTTP RSS link.
I don't know what's wrong with it.
Is there any specific error logs about the RSS plugins so I can check what is the problem?

### PR DESCRIPTION
**Pull request by kaso17**
Fixed #1247/#1196 for me

### CODE REVIEW

**Comment by Novik** [comment]
Thanks, but we have two bad points here.
1) You changed http request, but we also have https.
2) Port number should not be included, when we use default port (80 for http and 443 for https). RFC doesn't require this directly, but most of browsers uses this approach.
Please, correct your pull request.

**Comment by kaso17** [comment]
The latest change should take care of the two points.

**Comment by Nodens-** [comment]
This last commit breaks SSL on RSS feeds for me. Reverting the commit fixes the issue.
Let me know if you need more information for debugging.

Running on Fedora 25 with:
apache 2.4.23
php 7.0.13
curl/libcurl 7.51.0

**Comment by kaso17** [comment]
can you share the feed URL?
If not please let us know the server port and the server software.

**Comment by kaso17** [comment]
Never mind, @gromez already fixed my typo with dac8676322d9a896741059f95f5118a4410e2001

**Comment by Nodens-** [comment]
Indeed, I can verify it is working properly now :)

**Pull request merged**
