### PR TITLE
#2539 - yougetsignal down

### PR DESCRIPTION
**Pull request by Rathorian**

### CODE REVIEW

**Comment by koblack** [comment]
yougetsignal is down forever or is it a temporary downtime?

**Comment by Rathorian** [comment]
> yougetsignal is down forever or is it a temporary downtime?

I don't know but it's been down since July 23rd.

**Comment by stickz** [comment]
Thank you. Agreed. We will change this to portchecker.

**Comment by Rathorian** [comment]
I just saw that the `yougetsignal` site is working again, I don't know if you want to go back to it or keep `portchecker`?

**Comment by stickz** [comment]
> I just saw that the `yougetsignal` site is working again, I don't know if you want to go back to it or keep `portchecker`?

We are going to switch to `portchecker`. This a more reliable option. The uptime of `yougetsignal` is not satisfactory. It was down for over a week.

**Pull request merged**
