### PR TITLE
fix for rtorrent 0.9.8 compatibility

### PR DESCRIPTION
**Pull request by Micdu70**
rtorrent "feature-bind" branch (rtorrent 0.9.7) => API version = 10 with changed commands names
rtorrent 0.9.8 official release / "master" branch => API version = 10 without changed commands names

EDIT: See rakshasa/rtorrent#896 for rTorrent author's explanation.

### CODE REVIEW

**Comment by Novik** [comment]
I thik we should remove this code (for theWebUI.systemInfo.rTorrent.apiVersion>=10) at all.
Tommorow rakshasa will add yet one branch, with another command set (why he rename them so often?)
We will not support something exclude master branch + official releases.

**Comment by rtorrentuser** [comment]
> I thik we should remove this code (for theWebUI.systemInfo.rTorrent.apiVersion>=10) at all.

Rakshasa has bumped feature-bind branch api version to 11.
https://github.com/rakshasa/rtorrent/commit/a352524270de344038d3dbe9623f2b896dbaa838

**Comment by exrat** [comment]
( english bazaar inside ! )
yes it's ok for 11 with 0.9.7 & 0.9.8
`if(theWebUI.systemInfo.rTorrent.apiVersion>=11)`
`if($this->apiVersion >= 11)`

**Comment by Novik** [comment]
I made corresponding changes here - https://github.com/Novik/ruTorrent/commit/ec8d8f1887af57793a671258072b59193a5d8d6c

Thanks to all.

**Pull request closed without merging**
