### PR TITLE
added m2ts and iso for BluRay Raw Files

### PR DESCRIPTION
**Pull request by abixalmon**
added m2ts and iso for BluRay Raw Files

### CODE REVIEW

**Comment by s-c-o-o-t** [comment]
how do you add  or merge in ubuntu ? simpliest way, dont want to mess up :)

**Comment by abixalmon** [comment]
simplest solution is 
```sed -i 's/,"ts"/,"ts","m2ts","iso"/' /var/www/rutorrent/plugins/screenshots/conf.php```

Replace ```/var/www/rutorrent``` with your rutorrent path

**Comment by s-c-o-o-t** [comment]
thank you ill give it a try  :)

**Comment by Novik** [comment]
1) Set of extensions have dependence from the ffmpeg compile options.
2) You may add these changes to the individual configuration of plugin, see https://github.com/Novik/ruTorrent/wiki/Plugins#configuration for details.

**Pull request closed without merging**
