### PR TITLE
Update YggTorrent.php

### PR DESCRIPTION
**Pull request by KDTheory**
Fix wrong url

### CODE REVIEW

**Comment by Micdu70** [comment]
Do you really know what are you doing?

**Comment by KDTheory** [comment]
@Micdu70 yggtorrent.to does not work that way so we need to put the exact link in order to make it work. Do you have an other idea ?

**Comment by Micdu70** [comment]
If you get torrents search result from Ygg but you can't download them, changing extsearch engine file is not needed.
To fix download from extsearch, you only need to fix loginmgr account file.

**Comment by KDTheory** [comment]
Oh yeah you right i change the wrong one i close this one

**Pull request closed without merging**
