### PR TITLE
Added magnet register

### PR DESCRIPTION
**Pull request by Windkracht8**
Use registerProtocolHandler to register magnet links to rutorrent.
This change will make the browser ask the user to use rutorrent to handle magnet links on other pages. The response from addtorrent.php should be different when this happens, I will work on this some other time.

### CODE REVIEW

**Comment by Novik** [comment]
http://caniuse.com/#search=registerProtocolHandler

**Comment by Windkracht8** [comment]
I have added a check if the function is available before using it.

**Comment by Novik** [comment]
Sorry, but this is very strange check...
```
if(typeof navigator.registerProtocolHandler == 'function'){
...
			if((typeof navigator.isProtocolHandlerRegistered != 'function')  // How this may be here ???
}
```

**Comment by enoch85** [comment]
@Windkracht8 Great fix, but this only opens up a new Chrome browser window for me. Is there any way I can hardcode the path, or fix the code so that it opens up ruTorrent at the location I'm using it?

**Comment by Windkracht8** [comment]
@enoch85 I do not think so. The call only excepts protocol, url and title. The rest is up to the browser to do what they think is best.

**Comment by enoch85** [comment]
@Windkracht8 Thanks, will check my browser defaults.

**Comment by enoch85** [comment]
@Windkracht8 Hmm, couldn't find any. :( Could you provide any guidance maybe?

**Comment by Windkracht8** [comment]
@enoch85 I do not think you can change this behaviour, at least not without altering the browser code itself. In FF it will open the link in the same window/tab.

**Comment by enoch85** [comment]
Too bad. :/

**Pull request merged**
